- 👋 Hi, I’m @DayJayyy
- 👀 I’m interested in dancing, rapping and singing...
- 🌱 I’m currently learning as a senior high school student ...
- 💞️ I’m looking to collaborate on someone who's talented like me...
- 📫 How to reach me, just email me at dayjayyy143@gmail.com ...

<!---
DayJayyy/DayJayyy is a ✨ special ✨ repository because its `README.md` (this file) appears on your GitHub profile.
You can click the Preview link to take a look at your changes.
--->
